---
title: "Ponderosa Greenhouse Analysis"
author: "Katie Nigro"
date: "8/19/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load packages

```{r}
#load packages
library(tidyr)
library(ggplot2)
library(dplyr)
library(readr)
library(lubridate)
```

#Length Measurements

```{r}
#read in data

measurement_data <- read_csv("greenhouse data/greenhouse_measurements.csv", col_types = "cddccDdddddddddddddddddcc")
head(measurement_data)

unique(measurement_data$mom) #there are 43 families total

View(measurement_data %>% 
  filter(treatment == "DROUGHT") %>% 
  group_by(mom) %>% 
  summarise(n_drought = n()/3))

View(measurement_data %>% 
  filter(treatment == "WATERED") %>% 
  group_by(mom) %>% 
  summarise(n_water = n()/3))

```

```{r}
#get data in order
measurement_data2<- measurement_data %>% 
  unite("rack","row","column","mom", sep="_", col="uid", remove=FALSE) %>% 
  filter(!(mom == "blank" | mom == "BLANK" | mom == "")) %>% 
  mutate(pop = substr(mom,0,3))

```

```{r}
#make summarized dataset
measurement_sum <- measurement_data2 %>% 
  rowwise() %>% 
  mutate(ave.cotyl.length = mean(c(cotyl.length1,cotyl.length2, cotyl.length3),na.rm=TRUE),
         max.prim.needle.length = pmax(needle.length1, needle.length2, needle.length3),
         max.true.needle.length = max(c(true.need.length1,true.need.length2,true.need.length3,true.need.length4,true.need.length5,true.need.length6,true.need.length7,true.need.length8,true.need.length9,true.need.length10),na.rm=TRUE),
         ave.true.needle.length = mean(c(true.need.length1,true.need.length2,true.need.length3,true.need.length4,true.need.length5,true.need.length6,true.need.length7,true.need.length8,true.need.length9,true.need.length10),na.rm=TRUE)) %>% 
  dplyr::select(-cotyl.length1, -cotyl.length2, -cotyl.length3,-needle.length1, -needle.length2, -needle.length3,-contains("true.need.length"))

head(measurement_sum)

unique(measurement_sum$mom)

#compare stem lengths between families, populations and water treatments
ggplot(measurement_sum, aes(x=mom, y=stem.length, fill=treatment))+
  geom_boxplot()

ggplot(measurement_sum, aes(x=pop, y=stem.length, fill=treatment))+
  geom_boxplot()

#compare cotyledon length 
ggplot(measurement_sum, aes(x=mom, y=ave.cotyl.length, fill=treatment))+
  geom_boxplot()

ggplot(measurement_sum, aes(x=pop, y=ave.cotyl.length, fill=treatment))+
  geom_boxplot()

#compare needle length - need to do this by date
##first create dataframe with difference in needle length between dates
prim.needle.comp <- measurement_sum %>% 
  filter(date < '2021-07-30') %>% 
  left_join(measurement_sum %>% 
              filter(date > '2021-07-30'), by="uid") %>% 
  filter(!is.na(max.prim.needle.length.y)) %>% 
  mutate(prim.needle.growth = (max.prim.needle.length.y - max.prim.needle.length.x)/as.numeric(date.y - date.x)) %>% 
    mutate(prim.needle.growth = if_else(prim.needle.growth < 0, 0, prim.needle.growth))

ggplot(prim.needle.comp, aes(x=pop.x, y=max.prim.needle.length.y, fill=treatment.x))+
  geom_boxplot()

ggplot(prim.needle.comp, aes(x=pop.x, y=prim.needle.growth, fill=treatment.x))+
  geom_boxplot()

##remaining sample size 
sample.size.drought.start <- measurement_sum %>% 
  filter(treatment=="DROUGHT", date < '2021-07-30') %>% 
  group_by(mom) %>% 
  summarise(n.start = n()) %>% 
  mutate(trt = "drought")
sample.size.water.start<- measurement_sum %>% 
  filter(treatment=="WATERED", date < '2021-07-30') %>% 
  group_by(mom) %>% 
  summarise(n.start = n()) %>% 
    mutate(trt = "water")

sample.size.drought.aug <- prim.needle.comp %>% 
  filter(treatment.x == "DROUGHT") %>% 
  group_by(mom.x) %>% 
  summarise(n.aug = n()) %>% 
  mutate(trt = "drought")
sample.size.water.aug<- prim.needle.comp %>% 
  filter(treatment.x == "WATERED") %>% 
  group_by(mom.x) %>% 
  summarise(n.aug = n()) %>% 
    mutate(trt = "water")

sample.size <- sample.size.drought.start %>% 
  left_join(sample.size.drought.aug, by=c("mom" = "mom.x", "trt")) %>% 
  bind_rows(sample.size.water.start %>% 
  left_join(sample.size.water.aug, by = c("mom" = "mom.x","trt"))) %>% 
  mutate(prop.died = (n.start - n.aug)/n.start) %>% 
  mutate(pop = substr(mom,0,3))

sample.size

ggplot(sample.size, aes(x=pop, y=prop.died, fill=trt))+
  geom_boxplot()


#write.csv(sample.start, "C:/Users/Katie/Google Drive/Ponderosa seed project/data/greenhouse exp/sample.size.csv")

```

#Root-Shoot Biomass

```{r}
#read in data
rs_data <- read_csv("greenhouse data/ponderosa_root_elongation.csv")
```

```{r}
ggplot(rs_data, aes(x=trt,y=dry_total_mg))+
  geom_boxplot()

ggplot(rs_data, aes(x=trt,y=dry_root_mg))+
  geom_boxplot()

ggplot(rs_data, aes(x=trt,y=dry_shoot_mg))+
  geom_boxplot()
```

```{r}
#look at root:shoot ratio

rs_data <- rs_data %>% 
  mutate(root.shoot = dry_root_mg/dry_shoot_mg)
rs_data$pop <- substr(rs_data$family, 0,3)

ggplot(rs_data, aes(x=family, fill=trt, y=root.shoot))+
  geom_bar(stat='identity', position = 'dodge')

ggplot(rs_data, aes(x=trt, y=root.shoot))+
  geom_boxplot()

ggplot(rs_data, aes(x=pop, fill=trt, y=root.shoot))+
  geom_boxplot()
```

#Soil Water Distribution

Need to measure volume in each section of conetainer to scale these measurements. 

```{r}
rs_data <- rs_data %>% 
  mutate(water1 = wet_weight1_mg - dry_weight1_mg,
         water2 = wet_weight2_mg - dry_weight2_mg,
         water3 = wet_weight3_mg - dry_weight3_mg)

water_wts <- rs_data %>% 
  select(trt, family, water1, water2, water3) %>% 
  pivot_longer(cols=c(water1, water2, water3), names_to = "section", values_to = "water_weight")

ggplot(water_wts, aes(fill=trt, y=water_weight, x=section))+
  geom_boxplot()

ggplot(water_wts, aes(x=family, y=water_weight, fill=section))+
  facet_wrap(~trt)+
  geom_bar(stat='identity')+
  theme(axis.text.x = element_text(angle=45, vjust=1))

```

#Survival after water stopped

```{r}
deathdates <- read.csv("greenhouse data/greenhouse_deathdates.csv") %>% 
  mutate(death.date = mdy(death.date)) %>% 
  mutate(pop = substr(MOM,0,3)) %>% 
  mutate(surv.days = as.numeric(death.date - ymd("2021-09-20"))) %>% 
  filter(!is.na(death.date))

ggplot(deathdates, aes(x=pop,fill=MOM, y=surv.days))+
  geom_boxplot(position = 'dodge')

```

#Gas Exchange

```{r}
gas_july <- read.csv("greenhouse data/licor/kn_pond_july_areacorrected.xls.csv")
gas_sept <- read.csv("greenhouse data/licor/kn_pond_sept_areacorrected.csv")

colnames(gas_july)
colnames(gas_sept)

gas_all<- bind_rows(gas_july %>% 
  select(Obs, family, treatment, date, HHMMSS, Photo, Cond, Ci, Area, Tair, Tleaf, CO2R, CO2S, H2OR, H2OS, RH_R, RH_S, Flow, PARi) %>% 
    mutate(Area = as.numeric(Area)),
  gas_sept %>%
    rename("Obs"="ï..Obs") %>% 
  select(Obs, family, treatment, date, HHMMSS, Photo, Cond, Ci, Area, Tair, Tleaf, CO2R, CO2S, H2OR, H2OS, RH_R, RH_S, Flow, PARi)) %>% 
  filter(!is.na(Photo)) %>% 
  mutate(pop=substr(family, 0,3))

gas_all %>% 
  group_by(date) %>% 
  summarise(n_family = length(unique(family)))

ggplot(gas_all, aes(x=date, y=Photo, fill=treatment))+
  geom_boxplot()
ggplot(gas_all, aes(x=date, y=Cond, fill=treatment,color=pop))+
  geom_boxplot()

```



#Looking at sample size for Sarah Hart

```{r}
sample <- read.csv("C:/Users/Katie/Google Drive/Ponderosa seed project/data/greenhouse exp/seedling_tally_forSarah.csv")

sample.long <- sample %>% 
  pivot_longer(field.potting:field.sand.LHLH) %>% 
  rename(pop = ï..pop)

ggplot(sample.long %>% group_by(pop) %>% dplyr::summarise(sum = sum(value, na.rm = TRUE)), aes(x=pop, y=sum))+
  geom_bar(stat='identity')

ggplot(sample.long, aes(x=pop, y=value, fill=name))+
  geom_bar(stat='identity')+
  ylab("Number of seedlings")+
  theme_bw()+
  theme(text=element_text(size=26))

ggplot(sample.long, aes(x=family, y=value, fill=name))+
  geom_bar(stat='identity')+
  ylab("Number of seedlings")+
  theme_bw()+
  theme(text=element_text(size=20),axis.text.x = element_text(angle=45, vjust=0.6))

sample.long %>% group_by(pop) %>% summarise(sum.pop=sum(value,na.rm=TRUE))
familytable <- sample.long %>% group_by(family) %>% summarise(sum.pop=sum(value,na.rm=TRUE))
write.csv(familytable,"C:/Users/Katie/Documents/familytable.csv")

```